version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - VITE_SERVER_URL=${VITE_SERVER_URL}
        - VITE_WEB_URL=${VITE_WEB_URL}
    container_name: issue-tracker
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped