/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _protectedRouteImport } from './routes/__protected'
import { Route as _authRouteImport } from './routes/__auth'
import { Route as _protectedIndexRouteImport } from './routes/__protected/index'
import { Route as _protectedSettingsRouteImport } from './routes/__protected/settings'
import { Route as _protectedDashboardRouteImport } from './routes/__protected/dashboard'
import { Route as _protected_adminRouteImport } from './routes/__protected/__admin'
import { Route as _authResetPasswordRouteImport } from './routes/__auth/reset-password'
import { Route as _authLoginRouteImport } from './routes/__auth/login'
import { Route as _authForgotPasswordRouteImport } from './routes/__auth/forgot-password'
import { Route as _protectedProjectsIndexRouteImport } from './routes/__protected/projects/index'
import { Route as _protectedIssuesIndexRouteImport } from './routes/__protected/issues/index'
import { Route as _protectedProjectsCreateProjectRouteImport } from './routes/__protected/projects/create-project'
import { Route as _protectedIssuesCreateIsssueRouteImport } from './routes/__protected/issues/create-isssue'
import { Route as _protected_adminUserManagementIndexRouteImport } from './routes/__protected/__admin/user-management.index'
import { Route as _protectedProjectsEditProjectIdRouteImport } from './routes/__protected/projects/edit-project.$id'
import { Route as _protectedIssuesEditIssueIdRouteImport } from './routes/__protected/issues/edit-issue.$id'
import { Route as _protected_adminUserManagementCreateUserRouteImport } from './routes/__protected/__admin/user-management.create-user'
import { Route as _protected_adminUserManagementEditUserIdRouteImport } from './routes/__protected/__admin/user-management.edit-user.$id'

const _protectedRoute = _protectedRouteImport.update({
  id: '/__protected',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRoute = _authRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedIndexRoute = _protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedSettingsRoute = _protectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedDashboardRoute = _protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => _protectedRoute,
} as any)
const _protected_adminRoute = _protected_adminRouteImport.update({
  id: '/__admin',
  getParentRoute: () => _protectedRoute,
} as any)
const _authResetPasswordRoute = _authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => _authRoute,
} as any)
const _authLoginRoute = _authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => _authRoute,
} as any)
const _authForgotPasswordRoute = _authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => _authRoute,
} as any)
const _protectedProjectsIndexRoute = _protectedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedIssuesIndexRoute = _protectedIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedProjectsCreateProjectRoute =
  _protectedProjectsCreateProjectRouteImport.update({
    id: '/projects/create-project',
    path: '/projects/create-project',
    getParentRoute: () => _protectedRoute,
  } as any)
const _protectedIssuesCreateIsssueRoute =
  _protectedIssuesCreateIsssueRouteImport.update({
    id: '/issues/create-isssue',
    path: '/issues/create-isssue',
    getParentRoute: () => _protectedRoute,
  } as any)
const _protected_adminUserManagementIndexRoute =
  _protected_adminUserManagementIndexRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => _protected_adminRoute,
  } as any)
const _protectedProjectsEditProjectIdRoute =
  _protectedProjectsEditProjectIdRouteImport.update({
    id: '/projects/edit-project/$id',
    path: '/projects/edit-project/$id',
    getParentRoute: () => _protectedRoute,
  } as any)
const _protectedIssuesEditIssueIdRoute =
  _protectedIssuesEditIssueIdRouteImport.update({
    id: '/issues/edit-issue/$id',
    path: '/issues/edit-issue/$id',
    getParentRoute: () => _protectedRoute,
  } as any)
const _protected_adminUserManagementCreateUserRoute =
  _protected_adminUserManagementCreateUserRouteImport.update({
    id: '/user-management/create-user',
    path: '/user-management/create-user',
    getParentRoute: () => _protected_adminRoute,
  } as any)
const _protected_adminUserManagementEditUserIdRoute =
  _protected_adminUserManagementEditUserIdRouteImport.update({
    id: '/user-management/edit-user/$id',
    path: '/user-management/edit-user/$id',
    getParentRoute: () => _protected_adminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof _authForgotPasswordRoute
  '/login': typeof _authLoginRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/dashboard': typeof _protectedDashboardRoute
  '/settings': typeof _protectedSettingsRoute
  '/': typeof _protectedIndexRoute
  '/issues/create-isssue': typeof _protectedIssuesCreateIsssueRoute
  '/projects/create-project': typeof _protectedProjectsCreateProjectRoute
  '/issues': typeof _protectedIssuesIndexRoute
  '/projects': typeof _protectedProjectsIndexRoute
  '/user-management/create-user': typeof _protected_adminUserManagementCreateUserRoute
  '/issues/edit-issue/$id': typeof _protectedIssuesEditIssueIdRoute
  '/projects/edit-project/$id': typeof _protectedProjectsEditProjectIdRoute
  '/user-management': typeof _protected_adminUserManagementIndexRoute
  '/user-management/edit-user/$id': typeof _protected_adminUserManagementEditUserIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof _authForgotPasswordRoute
  '/login': typeof _authLoginRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/dashboard': typeof _protectedDashboardRoute
  '/settings': typeof _protectedSettingsRoute
  '/': typeof _protectedIndexRoute
  '/issues/create-isssue': typeof _protectedIssuesCreateIsssueRoute
  '/projects/create-project': typeof _protectedProjectsCreateProjectRoute
  '/issues': typeof _protectedIssuesIndexRoute
  '/projects': typeof _protectedProjectsIndexRoute
  '/user-management/create-user': typeof _protected_adminUserManagementCreateUserRoute
  '/issues/edit-issue/$id': typeof _protectedIssuesEditIssueIdRoute
  '/projects/edit-project/$id': typeof _protectedProjectsEditProjectIdRoute
  '/user-management': typeof _protected_adminUserManagementIndexRoute
  '/user-management/edit-user/$id': typeof _protected_adminUserManagementEditUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth': typeof _authRouteWithChildren
  '/__protected': typeof _protectedRouteWithChildren
  '/__auth/forgot-password': typeof _authForgotPasswordRoute
  '/__auth/login': typeof _authLoginRoute
  '/__auth/reset-password': typeof _authResetPasswordRoute
  '/__protected/__admin': typeof _protected_adminRouteWithChildren
  '/__protected/dashboard': typeof _protectedDashboardRoute
  '/__protected/settings': typeof _protectedSettingsRoute
  '/__protected/': typeof _protectedIndexRoute
  '/__protected/issues/create-isssue': typeof _protectedIssuesCreateIsssueRoute
  '/__protected/projects/create-project': typeof _protectedProjectsCreateProjectRoute
  '/__protected/issues/': typeof _protectedIssuesIndexRoute
  '/__protected/projects/': typeof _protectedProjectsIndexRoute
  '/__protected/__admin/user-management/create-user': typeof _protected_adminUserManagementCreateUserRoute
  '/__protected/issues/edit-issue/$id': typeof _protectedIssuesEditIssueIdRoute
  '/__protected/projects/edit-project/$id': typeof _protectedProjectsEditProjectIdRoute
  '/__protected/__admin/user-management/': typeof _protected_adminUserManagementIndexRoute
  '/__protected/__admin/user-management/edit-user/$id': typeof _protected_adminUserManagementEditUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/'
    | '/issues/create-isssue'
    | '/projects/create-project'
    | '/issues'
    | '/projects'
    | '/user-management/create-user'
    | '/issues/edit-issue/$id'
    | '/projects/edit-project/$id'
    | '/user-management'
    | '/user-management/edit-user/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/'
    | '/issues/create-isssue'
    | '/projects/create-project'
    | '/issues'
    | '/projects'
    | '/user-management/create-user'
    | '/issues/edit-issue/$id'
    | '/projects/edit-project/$id'
    | '/user-management'
    | '/user-management/edit-user/$id'
  id:
    | '__root__'
    | '/__auth'
    | '/__protected'
    | '/__auth/forgot-password'
    | '/__auth/login'
    | '/__auth/reset-password'
    | '/__protected/__admin'
    | '/__protected/dashboard'
    | '/__protected/settings'
    | '/__protected/'
    | '/__protected/issues/create-isssue'
    | '/__protected/projects/create-project'
    | '/__protected/issues/'
    | '/__protected/projects/'
    | '/__protected/__admin/user-management/create-user'
    | '/__protected/issues/edit-issue/$id'
    | '/__protected/projects/edit-project/$id'
    | '/__protected/__admin/user-management/'
    | '/__protected/__admin/user-management/edit-user/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRoute: typeof _authRouteWithChildren
  _protectedRoute: typeof _protectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__protected': {
      id: '/__protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _protectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected/': {
      id: '/__protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _protectedIndexRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/settings': {
      id: '/__protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _protectedSettingsRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/dashboard': {
      id: '/__protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _protectedDashboardRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/__admin': {
      id: '/__protected/__admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _protected_adminRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__auth/reset-password': {
      id: '/__auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof _authResetPasswordRouteImport
      parentRoute: typeof _authRoute
    }
    '/__auth/login': {
      id: '/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _authLoginRouteImport
      parentRoute: typeof _authRoute
    }
    '/__auth/forgot-password': {
      id: '/__auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _authForgotPasswordRouteImport
      parentRoute: typeof _authRoute
    }
    '/__protected/projects/': {
      id: '/__protected/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof _protectedProjectsIndexRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/issues/': {
      id: '/__protected/issues/'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof _protectedIssuesIndexRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/projects/create-project': {
      id: '/__protected/projects/create-project'
      path: '/projects/create-project'
      fullPath: '/projects/create-project'
      preLoaderRoute: typeof _protectedProjectsCreateProjectRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/issues/create-isssue': {
      id: '/__protected/issues/create-isssue'
      path: '/issues/create-isssue'
      fullPath: '/issues/create-isssue'
      preLoaderRoute: typeof _protectedIssuesCreateIsssueRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/__admin/user-management/': {
      id: '/__protected/__admin/user-management/'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof _protected_adminUserManagementIndexRouteImport
      parentRoute: typeof _protected_adminRoute
    }
    '/__protected/projects/edit-project/$id': {
      id: '/__protected/projects/edit-project/$id'
      path: '/projects/edit-project/$id'
      fullPath: '/projects/edit-project/$id'
      preLoaderRoute: typeof _protectedProjectsEditProjectIdRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/issues/edit-issue/$id': {
      id: '/__protected/issues/edit-issue/$id'
      path: '/issues/edit-issue/$id'
      fullPath: '/issues/edit-issue/$id'
      preLoaderRoute: typeof _protectedIssuesEditIssueIdRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/__admin/user-management/create-user': {
      id: '/__protected/__admin/user-management/create-user'
      path: '/user-management/create-user'
      fullPath: '/user-management/create-user'
      preLoaderRoute: typeof _protected_adminUserManagementCreateUserRouteImport
      parentRoute: typeof _protected_adminRoute
    }
    '/__protected/__admin/user-management/edit-user/$id': {
      id: '/__protected/__admin/user-management/edit-user/$id'
      path: '/user-management/edit-user/$id'
      fullPath: '/user-management/edit-user/$id'
      preLoaderRoute: typeof _protected_adminUserManagementEditUserIdRouteImport
      parentRoute: typeof _protected_adminRoute
    }
  }
}

interface _authRouteChildren {
  _authForgotPasswordRoute: typeof _authForgotPasswordRoute
  _authLoginRoute: typeof _authLoginRoute
  _authResetPasswordRoute: typeof _authResetPasswordRoute
}

const _authRouteChildren: _authRouteChildren = {
  _authForgotPasswordRoute: _authForgotPasswordRoute,
  _authLoginRoute: _authLoginRoute,
  _authResetPasswordRoute: _authResetPasswordRoute,
}

const _authRouteWithChildren = _authRoute._addFileChildren(_authRouteChildren)

interface _protected_adminRouteChildren {
  _protected_adminUserManagementCreateUserRoute: typeof _protected_adminUserManagementCreateUserRoute
  _protected_adminUserManagementIndexRoute: typeof _protected_adminUserManagementIndexRoute
  _protected_adminUserManagementEditUserIdRoute: typeof _protected_adminUserManagementEditUserIdRoute
}

const _protected_adminRouteChildren: _protected_adminRouteChildren = {
  _protected_adminUserManagementCreateUserRoute:
    _protected_adminUserManagementCreateUserRoute,
  _protected_adminUserManagementIndexRoute:
    _protected_adminUserManagementIndexRoute,
  _protected_adminUserManagementEditUserIdRoute:
    _protected_adminUserManagementEditUserIdRoute,
}

const _protected_adminRouteWithChildren =
  _protected_adminRoute._addFileChildren(_protected_adminRouteChildren)

interface _protectedRouteChildren {
  _protected_adminRoute: typeof _protected_adminRouteWithChildren
  _protectedDashboardRoute: typeof _protectedDashboardRoute
  _protectedSettingsRoute: typeof _protectedSettingsRoute
  _protectedIndexRoute: typeof _protectedIndexRoute
  _protectedIssuesCreateIsssueRoute: typeof _protectedIssuesCreateIsssueRoute
  _protectedProjectsCreateProjectRoute: typeof _protectedProjectsCreateProjectRoute
  _protectedIssuesIndexRoute: typeof _protectedIssuesIndexRoute
  _protectedProjectsIndexRoute: typeof _protectedProjectsIndexRoute
  _protectedIssuesEditIssueIdRoute: typeof _protectedIssuesEditIssueIdRoute
  _protectedProjectsEditProjectIdRoute: typeof _protectedProjectsEditProjectIdRoute
}

const _protectedRouteChildren: _protectedRouteChildren = {
  _protected_adminRoute: _protected_adminRouteWithChildren,
  _protectedDashboardRoute: _protectedDashboardRoute,
  _protectedSettingsRoute: _protectedSettingsRoute,
  _protectedIndexRoute: _protectedIndexRoute,
  _protectedIssuesCreateIsssueRoute: _protectedIssuesCreateIsssueRoute,
  _protectedProjectsCreateProjectRoute: _protectedProjectsCreateProjectRoute,
  _protectedIssuesIndexRoute: _protectedIssuesIndexRoute,
  _protectedProjectsIndexRoute: _protectedProjectsIndexRoute,
  _protectedIssuesEditIssueIdRoute: _protectedIssuesEditIssueIdRoute,
  _protectedProjectsEditProjectIdRoute: _protectedProjectsEditProjectIdRoute,
}

const _protectedRouteWithChildren = _protectedRoute._addFileChildren(
  _protectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authRoute: _authRouteWithChildren,
  _protectedRoute: _protectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
